// <auto-generated />
using GreenThumbFinal.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumbFinal.Migrations
{
    [DbContext(typeof(GreenThumbDbContext))]
    [Migration("20231206145117_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenThumbFinal.Models.Instructions", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"));

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantsId")
                        .HasColumnType("int");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantsId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 3
                        },
                        new
                        {
                            InstructionId = 3,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 4
                        },
                        new
                        {
                            InstructionId = 4,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 6
                        },
                        new
                        {
                            InstructionId = 5,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 7
                        },
                        new
                        {
                            InstructionId = 6,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 8
                        },
                        new
                        {
                            InstructionId = 7,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 9
                        },
                        new
                        {
                            InstructionId = 8,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 11
                        },
                        new
                        {
                            InstructionId = 9,
                            Info = "Consistent Watering, establish consistent watering and use room temperature water.",
                            PlantsId = 12
                        },
                        new
                        {
                            InstructionId = 10,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 1
                        },
                        new
                        {
                            InstructionId = 11,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 2
                        },
                        new
                        {
                            InstructionId = 12,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 3
                        },
                        new
                        {
                            InstructionId = 13,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 6
                        },
                        new
                        {
                            InstructionId = 14,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 8
                        },
                        new
                        {
                            InstructionId = 15,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 9
                        },
                        new
                        {
                            InstructionId = 16,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 10
                        },
                        new
                        {
                            InstructionId = 17,
                            Info = "Light Requirements, this plant require full sun.",
                            PlantsId = 12
                        },
                        new
                        {
                            InstructionId = 18,
                            Info = "Fertilization, follow a fertilization schedule suitable for your plants.",
                            PlantsId = 2
                        },
                        new
                        {
                            InstructionId = 19,
                            Info = "Fertilization, follow a fertilization schedule suitable for your plants.",
                            PlantsId = 4
                        },
                        new
                        {
                            InstructionId = 20,
                            Info = "Fertilization, follow a fertilization schedule suitable for your plants.",
                            PlantsId = 6
                        },
                        new
                        {
                            InstructionId = 21,
                            Info = "Fertilization, follow a fertilization schedule suitable for your plants.",
                            PlantsId = 8
                        },
                        new
                        {
                            InstructionId = 22,
                            Info = "Fertilization, follow a fertilization schedule suitable for your plants.",
                            PlantsId = 10
                        },
                        new
                        {
                            InstructionId = 23,
                            Info = "Fertilization, follow a fertilization schedule suitable for your plants.",
                            PlantsId = 12
                        },
                        new
                        {
                            InstructionId = 24,
                            Info = "Rotate Plants, rotate indoor plants periodically to ensure all sides receive adequate light.",
                            PlantsId = 4
                        },
                        new
                        {
                            InstructionId = 25,
                            Info = "Rotate Plants, rotate indoor plants periodically to ensure all sides receive adequate light.",
                            PlantsId = 8
                        },
                        new
                        {
                            InstructionId = 26,
                            Info = "Rotate Plants, rotate indoor plants periodically to ensure all sides receive adequate light.",
                            PlantsId = 12
                        },
                        new
                        {
                            InstructionId = 27,
                            Info = "Humidity, use a humidifier or mist the plant occasionally to maintain adequate moisture.",
                            PlantsId = 1
                        },
                        new
                        {
                            InstructionId = 28,
                            Info = "Humidity, use a humidifier or mist the plant occasionally to maintain adequate moisture.",
                            PlantsId = 3
                        },
                        new
                        {
                            InstructionId = 29,
                            Info = "Humidity, use a humidifier or mist the plant occasionally to maintain adequate moisture.",
                            PlantsId = 5
                        },
                        new
                        {
                            InstructionId = 30,
                            Info = "Humidity, use a humidifier or mist the plant occasionally to maintain adequate moisture.",
                            PlantsId = 7
                        },
                        new
                        {
                            InstructionId = 31,
                            Info = "Humidity, use a humidifier or mist the plant occasionally to maintain adequate moisture.",
                            PlantsId = 9
                        },
                        new
                        {
                            InstructionId = 32,
                            Info = "Humidity, use a humidifier or mist the plant occasionally to maintain adequate moisture.",
                            PlantsId = 11
                        },
                        new
                        {
                            InstructionId = 33,
                            Info = "Remove Dead Leaves and Flowers, regularly remove dead or yellowing leaves and spent flowers.",
                            PlantsId = 5
                        },
                        new
                        {
                            InstructionId = 34,
                            Info = "Remove Dead Leaves and Flowers, regularly remove dead or yellowing leaves and spent flowers.",
                            PlantsId = 9
                        },
                        new
                        {
                            InstructionId = 35,
                            Info = "Remove Dead Leaves and Flowers, regularly remove dead or yellowing leaves and spent flowers.",
                            PlantsId = 12
                        });
                });

            modelBuilder.Entity("GreenThumbFinal.Models.Plants", b =>
                {
                    b.Property<int>("PlantsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantsId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantsId = 1,
                            Name = "Marijuana"
                        },
                        new
                        {
                            PlantsId = 2,
                            Name = "Papaver somniferum"
                        },
                        new
                        {
                            PlantsId = 3,
                            Name = "Erythroxylum coca"
                        },
                        new
                        {
                            PlantsId = 4,
                            Name = "Psilocybe spp."
                        },
                        new
                        {
                            PlantsId = 5,
                            Name = "Lophophora williamsii"
                        },
                        new
                        {
                            PlantsId = 6,
                            Name = "Catha edulis"
                        },
                        new
                        {
                            PlantsId = 7,
                            Name = "Mitragyna speciosa"
                        },
                        new
                        {
                            PlantsId = 8,
                            Name = "Salvia"
                        },
                        new
                        {
                            PlantsId = 9,
                            Name = "Amanita muscaria"
                        },
                        new
                        {
                            PlantsId = 10,
                            Name = "Lactuca virosa"
                        },
                        new
                        {
                            PlantsId = 11,
                            Name = "Piper methysticum"
                        },
                        new
                        {
                            PlantsId = 12,
                            Name = "Areca catechu"
                        });
                });

            modelBuilder.Entity("GreenThumbFinal.Models.Instructions", b =>
                {
                    b.HasOne("GreenThumbFinal.Models.Plants", "Plants")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("GreenThumbFinal.Models.Plants", b =>
                {
                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
